// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtAZpsGPjugdM8jdKYKlVm5s6s6ynapnw',
    appId: '1:687319018874:web:bcfdb89e6fff5d4c5bfac3',
    messagingSenderId: '687319018874',
    projectId: 'somnia-123',
    authDomain: 'somnia-123.firebaseapp.com',
    storageBucket: 'somnia-123.firebasestorage.app',
    measurementId: 'G-7132NFN6RT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwE6lwPCG17RGQ-NQErLhibFlrpEB8yZM',
    appId: '1:687319018874:android:30eb46824469dec65bfac3',
    messagingSenderId: '687319018874',
    projectId: 'somnia-123',
    storageBucket: 'somnia-123.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXeYAXZYzIa_D40lKbaQIBfUNkKK6BK-c',
    appId: '1:687319018874:ios:3e39179e5d4ce5d95bfac3',
    messagingSenderId: '687319018874',
    projectId: 'somnia-123',
    storageBucket: 'somnia-123.firebasestorage.app',
    iosBundleId: 'com.example.somniaServer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXeYAXZYzIa_D40lKbaQIBfUNkKK6BK-c',
    appId: '1:687319018874:ios:3e39179e5d4ce5d95bfac3',
    messagingSenderId: '687319018874',
    projectId: 'somnia-123',
    storageBucket: 'somnia-123.firebasestorage.app',
    iosBundleId: 'com.example.somniaServer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtAZpsGPjugdM8jdKYKlVm5s6s6ynapnw',
    appId: '1:687319018874:web:c25e3935ce6e19a05bfac3',
    messagingSenderId: '687319018874',
    projectId: 'somnia-123',
    authDomain: 'somnia-123.firebaseapp.com',
    storageBucket: 'somnia-123.firebasestorage.app',
    measurementId: 'G-J67XSNSWWN',
  );
}
